/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        tertiary: 'hsl(var(--tertiary))',
        surface: 'hsl(var(--surface))',
        'surface-dim': 'hsl(var(--surface-dim))',
        'surface-bright': 'hsl(var(--surface-bright))',
        'surface-variant': 'hsl(var(--surface-variant))',
        'surface-tint': 'hsl(var(--surface-tint))',
        'surface-container-lowest': 'hsl(var(--surface-container-lowest))',
        'surface-container-low': 'hsl(var(--surface-container-low))',
        'surface-container': 'hsl(var(--surface-container))',
        'surface-container-high': 'hsl(var(--surface-container-high))',
        'surface-container-highest': 'hsl(var(--surface-container-highest))',
        'on-background': 'hsl(var(--on-background))',
        'on-surface': 'hsl(var(--on-surface))',
        'on-surface-variant': 'hsl(var(--on-surface-variant))',
        outline: 'hsl(var(--outline))',
        'outline-variant': 'hsl(var(--outline-variant))',
        'inverse-surface': 'hsl(var(--inverse-surface))',
        'inverse-on-surface': 'hsl(var(--inverse-on-surface))',
        'inverse-primary': 'hsl(var(--inverse-primary))',
        error: 'hsl(var(--error))',
        'error-container': 'hsl(var(--error-container))',
        'on-error': 'hsl(var(--on-error))',
        'on-error-container': 'hsl(var(--on-error-container))',
        success: {
          DEFAULT: 'hsl(var(--success))',
          foreground: 'hsl(var(--on-success))',
          container: 'hsl(var(--success-container))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          foreground: 'hsl(var(--on-warning))',
          container: 'hsl(var(--warning-container))',
        },
        'primary-container': 'hsl(var(--primary-container))',
        'on-primary': 'hsl(var(--on-primary))',
        'on-primary-container': 'hsl(var(--on-primary-container))',
        'primary-fixed': 'hsl(var(--primary-fixed))',
        'primary-fixed-dim': 'hsl(var(--primary-fixed-dim))',
        'on-primary-fixed': 'hsl(var(--on-primary-fixed))',
        'on-primary-fixed-variant': 'hsl(var(--on-primary-fixed-variant))',
        'secondary-container': 'hsl(var(--secondary-container))',
        'on-secondary': 'hsl(var(--on-secondary))',
        'on-secondary-container': 'hsl(var(--on-secondary-container))',
        'secondary-fixed': 'hsl(var(--secondary-fixed))',
        'secondary-fixed-dim': 'hsl(var(--secondary-fixed-dim))',
        'on-secondary-fixed': 'hsl(var(--on-secondary-fixed))',
        'on-secondary-fixed-variant': 'hsl(var(--on-secondary-fixed-variant))',
        'tertiary-container': 'hsl(var(--tertiary-container))',
        'on-tertiary': 'hsl(var(--on-tertiary))',
        'on-tertiary-container': 'hsl(var(--on-tertiary-container))',
        'tertiary-fixed': 'hsl(var(--tertiary-fixed))',
        'tertiary-fixed-dim': 'hsl(var(--tertiary-fixed-dim))',
        'on-tertiary-fixed': 'hsl(var(--on-tertiary-fixed))',
        'on-tertiary-fixed-variant': 'hsl(var(--on-tertiary-fixed-variant))',
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: '0.5rem',
        md: 'calc(0.5rem - 2px)',
        sm: 'calc(0.5rem - 4px)',
        DEFAULT: '0.25rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-newsreader)', 'Georgia', 'serif'],
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-newsreader)', 'serif'],
        label: ['var(--font-manrope)', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        pulse: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.5 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
