/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: '#f8f9fa',
        foreground: '#191c1d',
        "primary-container": "#4e5b6f",
        "surface": "#f8f9fa",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary": "#313e7e",
        "on-tertiary-container": "#c9d0ff",
        "surface-dim": "#d9dadb",
        "outline-variant": "#c5c5d4",
        "secondary-container": "#c9eadf",
        "on-primary-fixed": "#0e1c2e",
        "on-background": "#191c1d",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed": "#02201a",
        "primary-fixed": "#d6e3fc",
        "on-secondary-fixed-variant": "#2f4c44",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#525f74",
        "on-surface-variant": "#454652",
        "on-tertiary-fixed-variant": "#354282",
        "on-primary-fixed-variant": "#3a475b",
        "inverse-surface": "#2e3132",
        "error": "#ba1a1a",
        "on-secondary-container": "#4d6a62",
        "tertiary-container": "#495697",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#021355",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#dee1ff",
        "secondary-fixed-dim": "#adcdc3",
        "secondary": "#47645c",
        "primary": "#374457",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed": "#c9eadf",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed-dim": "#bac7df",
        "surface-container-low": "#f3f4f5",
        "on-surface": "#191c1d",
        "inverse-primary": "#bac7df",
        "on-primary-container": "#c5d3eb",
        "tertiary-fixed-dim": "#b9c3ff",
        "outline": "#757684",
        "surface-container-highest": "#e1e3e4",
        "surface-container": "#edeeef",
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: '0.5rem',
        md: 'calc(0.5rem - 2px)',
        sm: 'calc(0.5rem - 4px)',
        DEFAULT: '0.25rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['var(--font-manrope)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-newsreader)', 'Georgia', 'serif'],
        headline: ['var(--font-manrope)', 'sans-serif'],
        body: ['var(--font-newsreader)', 'serif'],
        label: ['var(--font-manrope)', 'sans-serif'],
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        pulse: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.5 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
